apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "syncthing.fullname" . }}-data
spec:
  storageClassName: {{ .Values.pvc.spec.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
  {{- toYaml .Values.pvc.spec.resources | nindent 4 }}
